dataset: products

file:
  format: csv
  header: true
  sep: ","
  quote: '"'
  escape: '"'
  multiLine: true
  mode: PERMISSIVE
  rescuedDataColumn: _rescued_data
  encoding: UTF-8
  ignoreLeadingWhiteSpace: true
  ignoreTrailingWhiteSpace: true

target:
  catalog: olist
  schema: bronze
  table: products